# coding: utf-8

"""
    ai& API

    Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from aiand.models.chat_completion_message_any_of import ChatCompletionMessageAnyOf
from aiand.models.chat_completion_message_any_of1 import ChatCompletionMessageAnyOf1
from aiand.models.chat_completion_message_any_of2 import ChatCompletionMessageAnyOf2
from aiand.models.chat_completion_message_any_of3 import ChatCompletionMessageAnyOf3
from aiand.models.chat_completion_message_any_of4 import ChatCompletionMessageAnyOf4
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

CHATCOMPLETIONMESSAGE_ANY_OF_SCHEMAS = ["ChatCompletionMessageAnyOf", "ChatCompletionMessageAnyOf1", "ChatCompletionMessageAnyOf2", "ChatCompletionMessageAnyOf3", "ChatCompletionMessageAnyOf4"]

class ChatCompletionMessage(BaseModel):
    """
    ChatCompletionMessage
    """

    # data type: ChatCompletionMessageAnyOf
    anyof_schema_1_validator: Optional[ChatCompletionMessageAnyOf] = None
    # data type: ChatCompletionMessageAnyOf1
    anyof_schema_2_validator: Optional[ChatCompletionMessageAnyOf1] = None
    # data type: ChatCompletionMessageAnyOf2
    anyof_schema_3_validator: Optional[ChatCompletionMessageAnyOf2] = None
    # data type: ChatCompletionMessageAnyOf3
    anyof_schema_4_validator: Optional[ChatCompletionMessageAnyOf3] = None
    # data type: ChatCompletionMessageAnyOf4
    anyof_schema_5_validator: Optional[ChatCompletionMessageAnyOf4] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ChatCompletionMessageAnyOf, ChatCompletionMessageAnyOf1, ChatCompletionMessageAnyOf2, ChatCompletionMessageAnyOf3, ChatCompletionMessageAnyOf4]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "ChatCompletionMessageAnyOf", "ChatCompletionMessageAnyOf1", "ChatCompletionMessageAnyOf2", "ChatCompletionMessageAnyOf3", "ChatCompletionMessageAnyOf4" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ChatCompletionMessage.model_construct()
        error_messages = []
        # validate data type: ChatCompletionMessageAnyOf
        if not isinstance(v, ChatCompletionMessageAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChatCompletionMessageAnyOf`")
        else:
            return v

        # validate data type: ChatCompletionMessageAnyOf1
        if not isinstance(v, ChatCompletionMessageAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChatCompletionMessageAnyOf1`")
        else:
            return v

        # validate data type: ChatCompletionMessageAnyOf2
        if not isinstance(v, ChatCompletionMessageAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChatCompletionMessageAnyOf2`")
        else:
            return v

        # validate data type: ChatCompletionMessageAnyOf3
        if not isinstance(v, ChatCompletionMessageAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChatCompletionMessageAnyOf3`")
        else:
            return v

        # validate data type: ChatCompletionMessageAnyOf4
        if not isinstance(v, ChatCompletionMessageAnyOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ChatCompletionMessageAnyOf4`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ChatCompletionMessage with anyOf schemas: ChatCompletionMessageAnyOf, ChatCompletionMessageAnyOf1, ChatCompletionMessageAnyOf2, ChatCompletionMessageAnyOf3, ChatCompletionMessageAnyOf4. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ChatCompletionMessageAnyOf] = None
        try:
            instance.actual_instance = ChatCompletionMessageAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ChatCompletionMessageAnyOf1] = None
        try:
            instance.actual_instance = ChatCompletionMessageAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ChatCompletionMessageAnyOf2] = None
        try:
            instance.actual_instance = ChatCompletionMessageAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[ChatCompletionMessageAnyOf3] = None
        try:
            instance.actual_instance = ChatCompletionMessageAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[ChatCompletionMessageAnyOf4] = None
        try:
            instance.actual_instance = ChatCompletionMessageAnyOf4.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ChatCompletionMessage with anyOf schemas: ChatCompletionMessageAnyOf, ChatCompletionMessageAnyOf1, ChatCompletionMessageAnyOf2, ChatCompletionMessageAnyOf3, ChatCompletionMessageAnyOf4. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ChatCompletionMessageAnyOf, ChatCompletionMessageAnyOf1, ChatCompletionMessageAnyOf2, ChatCompletionMessageAnyOf3, ChatCompletionMessageAnyOf4]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


