# coding: utf-8

"""
    ai& API

    Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from aiand.models.create_response_request_reasoning import CreateResponseRequestReasoning
from aiand.models.create_response_request_stop import CreateResponseRequestStop
from aiand.models.create_response_request_text import CreateResponseRequestText
from aiand.models.create_response_request_tool_choice import CreateResponseRequestToolChoice
from aiand.models.create_response_request_tools_inner import CreateResponseRequestToolsInner
from aiand.models.response_input import ResponseInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateResponseRequest(BaseModel):
    """
    CreateResponseRequest
    """ # noqa: E501
    model: StrictStr = Field(description="ID of the model to use for this response.")
    input: ResponseInput = Field(description="Text, image, or file inputs to the model. Can be a string or an array of input items.")
    instructions: Optional[StrictStr] = Field(default=None, description="A system (or developer) message inserted into the model's context.")
    stream: Optional[StrictBool] = Field(default=False, description="If true, response data will be streamed as server-sent events.")
    temperature: Optional[Union[Annotated[float, Field(le=2, strict=True, ge=0)], Annotated[int, Field(le=2, strict=True, ge=0)]]] = Field(default=None, description="Sampling temperature between 0 and 2. Higher values make output more random.")
    top_p: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Nucleus sampling: consider tokens with top_p probability mass.")
    max_output_tokens: Optional[StrictInt] = Field(default=None, description="Upper bound for tokens that can be generated, including visible output and reasoning tokens.")
    tools: Optional[List[CreateResponseRequestToolsInner]] = Field(default=None, description="An array of function tools the model may call while generating a response.")
    tool_choice: Optional[CreateResponseRequestToolChoice] = None
    parallel_tool_calls: Optional[StrictBool] = Field(default=None, description="Whether to allow the model to run tool calls in parallel.")
    reasoning: Optional[CreateResponseRequestReasoning] = None
    truncation: Optional[StrictStr] = Field(default=None, description="\"auto\" truncates input to fit context window. \"disabled\" (default) returns 400 if input exceeds context.")
    previous_response_id: Optional[StrictStr] = Field(default=None, description="ID of a previous response to continue a multi-turn conversation.")
    store: Optional[StrictBool] = Field(default=None, description="Whether to store the response for later retrieval via API.")
    metadata: Optional[Dict[str, StrictStr]] = Field(default=None, description="Set of key-value pairs for additional information.")
    text: Optional[CreateResponseRequestText] = None
    top_logprobs: Optional[Annotated[int, Field(le=20, strict=True, ge=0)]] = Field(default=None, description="Number of most likely tokens to return at each position (0-20).")
    seed: Optional[StrictInt] = Field(default=None, description="If specified, the system will attempt deterministic sampling.")
    stop: Optional[CreateResponseRequestStop] = None
    top_k: Optional[Annotated[int, Field(strict=True, ge=-1)]] = Field(default=None, description="Number of highest probability tokens to keep for top-k sampling. -1 to disable.")
    repetition_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Penalizes new tokens based on whether they appear in the generated text so far. Values > 1.0 penalize repetitions.")
    min_tokens: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Minimum number of tokens to generate before allowing a stop condition.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["model", "input", "instructions", "stream", "temperature", "top_p", "max_output_tokens", "tools", "tool_choice", "parallel_tool_calls", "reasoning", "truncation", "previous_response_id", "store", "metadata", "text", "top_logprobs", "seed", "stop", "top_k", "repetition_penalty", "min_tokens"]

    @field_validator('truncation')
    def truncation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'disabled']):
            raise ValueError("must be one of enum values ('auto', 'disabled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateResponseRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tools (list)
        _items = []
        if self.tools:
            for _item_tools in self.tools:
                if _item_tools:
                    _items.append(_item_tools.to_dict())
            _dict['tools'] = _items
        # override the default output from pydantic by calling `to_dict()` of tool_choice
        if self.tool_choice:
            _dict['tool_choice'] = self.tool_choice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reasoning
        if self.reasoning:
            _dict['reasoning'] = self.reasoning.to_dict()
        # override the default output from pydantic by calling `to_dict()` of text
        if self.text:
            _dict['text'] = self.text.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stop
        if self.stop:
            _dict['stop'] = self.stop.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if instructions (nullable) is None
        # and model_fields_set contains the field
        if self.instructions is None and "instructions" in self.model_fields_set:
            _dict['instructions'] = None

        # set to None if stream (nullable) is None
        # and model_fields_set contains the field
        if self.stream is None and "stream" in self.model_fields_set:
            _dict['stream'] = None

        # set to None if temperature (nullable) is None
        # and model_fields_set contains the field
        if self.temperature is None and "temperature" in self.model_fields_set:
            _dict['temperature'] = None

        # set to None if top_p (nullable) is None
        # and model_fields_set contains the field
        if self.top_p is None and "top_p" in self.model_fields_set:
            _dict['top_p'] = None

        # set to None if max_output_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_output_tokens is None and "max_output_tokens" in self.model_fields_set:
            _dict['max_output_tokens'] = None

        # set to None if parallel_tool_calls (nullable) is None
        # and model_fields_set contains the field
        if self.parallel_tool_calls is None and "parallel_tool_calls" in self.model_fields_set:
            _dict['parallel_tool_calls'] = None

        # set to None if truncation (nullable) is None
        # and model_fields_set contains the field
        if self.truncation is None and "truncation" in self.model_fields_set:
            _dict['truncation'] = None

        # set to None if previous_response_id (nullable) is None
        # and model_fields_set contains the field
        if self.previous_response_id is None and "previous_response_id" in self.model_fields_set:
            _dict['previous_response_id'] = None

        # set to None if store (nullable) is None
        # and model_fields_set contains the field
        if self.store is None and "store" in self.model_fields_set:
            _dict['store'] = None

        # set to None if top_logprobs (nullable) is None
        # and model_fields_set contains the field
        if self.top_logprobs is None and "top_logprobs" in self.model_fields_set:
            _dict['top_logprobs'] = None

        # set to None if seed (nullable) is None
        # and model_fields_set contains the field
        if self.seed is None and "seed" in self.model_fields_set:
            _dict['seed'] = None

        # set to None if stop (nullable) is None
        # and model_fields_set contains the field
        if self.stop is None and "stop" in self.model_fields_set:
            _dict['stop'] = None

        # set to None if top_k (nullable) is None
        # and model_fields_set contains the field
        if self.top_k is None and "top_k" in self.model_fields_set:
            _dict['top_k'] = None

        # set to None if repetition_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.repetition_penalty is None and "repetition_penalty" in self.model_fields_set:
            _dict['repetition_penalty'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateResponseRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "input": ResponseInput.from_dict(obj["input"]) if obj.get("input") is not None else None,
            "instructions": obj.get("instructions"),
            "stream": obj.get("stream") if obj.get("stream") is not None else False,
            "temperature": obj.get("temperature"),
            "top_p": obj.get("top_p"),
            "max_output_tokens": obj.get("max_output_tokens"),
            "tools": [CreateResponseRequestToolsInner.from_dict(_item) for _item in obj["tools"]] if obj.get("tools") is not None else None,
            "tool_choice": CreateResponseRequestToolChoice.from_dict(obj["tool_choice"]) if obj.get("tool_choice") is not None else None,
            "parallel_tool_calls": obj.get("parallel_tool_calls"),
            "reasoning": CreateResponseRequestReasoning.from_dict(obj["reasoning"]) if obj.get("reasoning") is not None else None,
            "truncation": obj.get("truncation"),
            "previous_response_id": obj.get("previous_response_id"),
            "store": obj.get("store"),
            "metadata": obj.get("metadata"),
            "text": CreateResponseRequestText.from_dict(obj["text"]) if obj.get("text") is not None else None,
            "top_logprobs": obj.get("top_logprobs"),
            "seed": obj.get("seed"),
            "stop": CreateResponseRequestStop.from_dict(obj["stop"]) if obj.get("stop") is not None else None,
            "top_k": obj.get("top_k"),
            "repetition_penalty": obj.get("repetition_penalty"),
            "min_tokens": obj.get("min_tokens")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


