# coding: utf-8

"""
    ai& API

    Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from aiand.models.chat_completion_message import ChatCompletionMessage
from aiand.models.create_chat_completion_request_response_format import CreateChatCompletionRequestResponseFormat
from aiand.models.create_chat_completion_request_stop import CreateChatCompletionRequestStop
from aiand.models.create_chat_completion_request_stream_options import CreateChatCompletionRequestStreamOptions
from aiand.models.create_chat_completion_request_tool_choice import CreateChatCompletionRequestToolChoice
from aiand.models.create_chat_completion_request_tools_inner import CreateChatCompletionRequestToolsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateChatCompletionRequest(BaseModel):
    """
    CreateChatCompletionRequest
    """ # noqa: E501
    model: StrictStr = Field(description="ID of the model to use for the chat completion.")
    messages: Annotated[List[ChatCompletionMessage], Field(min_length=1)] = Field(description="A list of messages comprising the conversation so far.")
    stream: Optional[StrictBool] = Field(default=False, description="If true, partial message deltas will be sent as server-sent events.")
    stream_options: Optional[CreateChatCompletionRequestStreamOptions] = None
    temperature: Optional[Union[Annotated[float, Field(le=2, strict=True, ge=0)], Annotated[int, Field(le=2, strict=True, ge=0)]]] = Field(default=None, description="Sampling temperature between 0 and 2. Higher values make output more random.")
    top_p: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Nucleus sampling: consider tokens with top_p probability mass.")
    n: Optional[Annotated[int, Field(le=128, strict=True, ge=1)]] = Field(default=None, description="How many chat completion choices to generate.")
    max_tokens: Optional[StrictInt] = Field(default=None, description="Maximum number of tokens to generate. Deprecated in favor of max_completion_tokens.")
    max_completion_tokens: Optional[StrictInt] = Field(default=None, description="Upper bound for tokens that can be generated, including visible output and reasoning tokens.")
    stop: Optional[CreateChatCompletionRequestStop] = None
    frequency_penalty: Optional[Union[Annotated[float, Field(le=2, strict=True, ge=-2)], Annotated[int, Field(le=2, strict=True, ge=-2)]]] = Field(default=None, description="Number between -2.0 and 2.0. Positive values penalize tokens based on existing frequency.")
    presence_penalty: Optional[Union[Annotated[float, Field(le=2, strict=True, ge=-2)], Annotated[int, Field(le=2, strict=True, ge=-2)]]] = Field(default=None, description="Number between -2.0 and 2.0. Positive values penalize tokens based on whether they appear in the text so far.")
    logprobs: Optional[StrictBool] = Field(default=None, description="Whether to return log probabilities of the output tokens.")
    top_logprobs: Optional[Annotated[int, Field(le=20, strict=True, ge=0)]] = Field(default=None, description="Number of most likely tokens to return at each position (0-20). Requires logprobs=true.")
    logit_bias: Optional[Dict[str, StrictInt]] = Field(default=None, description="Map of token IDs to bias values (-100 to 100) to modify likelihood of specified tokens.")
    response_format: Optional[CreateChatCompletionRequestResponseFormat] = None
    seed: Optional[StrictInt] = Field(default=None, description="If specified, the system will attempt deterministic sampling. Determinism is not guaranteed.")
    tools: Optional[List[CreateChatCompletionRequestToolsInner]] = Field(default=None, description="A list of tools the model may call.")
    tool_choice: Optional[CreateChatCompletionRequestToolChoice] = None
    parallel_tool_calls: Optional[StrictBool] = Field(default=None, description="Whether to enable parallel function calling during tool use.")
    reasoning_effort: Optional[StrictStr] = Field(default=None, description="Constrains reasoning effort for reasoning models. One of: none, minimal, low, medium, high, xhigh.")
    top_k: Optional[Annotated[int, Field(strict=True, ge=-1)]] = Field(default=None, description="Number of highest probability tokens to keep for top-k sampling. -1 to disable.")
    min_p: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="Minimum probability threshold relative to the top token. Tokens below this are filtered out. 0.0 to disable.")
    repetition_penalty: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Penalizes new tokens based on whether they appear in the generated text so far. Values > 1.0 penalize repetitions.")
    min_tokens: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Minimum number of tokens to generate before allowing a stop condition.")
    echo: Optional[StrictBool] = Field(default=None, description="If true, the prompt is prepended to the generated output.")
    user: Optional[StrictStr] = Field(default=None, description="A unique identifier representing your end-user.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["model", "messages", "stream", "stream_options", "temperature", "top_p", "n", "max_tokens", "max_completion_tokens", "stop", "frequency_penalty", "presence_penalty", "logprobs", "top_logprobs", "logit_bias", "response_format", "seed", "tools", "tool_choice", "parallel_tool_calls", "reasoning_effort", "top_k", "min_p", "repetition_penalty", "min_tokens", "echo", "user"]

    @field_validator('reasoning_effort')
    def reasoning_effort_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'minimal', 'low', 'medium', 'high', 'xhigh']):
            raise ValueError("must be one of enum values ('none', 'minimal', 'low', 'medium', 'high', 'xhigh')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateChatCompletionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item_messages in self.messages:
                if _item_messages:
                    _items.append(_item_messages.to_dict())
            _dict['messages'] = _items
        # override the default output from pydantic by calling `to_dict()` of stream_options
        if self.stream_options:
            _dict['stream_options'] = self.stream_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stop
        if self.stop:
            _dict['stop'] = self.stop.to_dict()
        # override the default output from pydantic by calling `to_dict()` of response_format
        if self.response_format:
            _dict['response_format'] = self.response_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tools (list)
        _items = []
        if self.tools:
            for _item_tools in self.tools:
                if _item_tools:
                    _items.append(_item_tools.to_dict())
            _dict['tools'] = _items
        # override the default output from pydantic by calling `to_dict()` of tool_choice
        if self.tool_choice:
            _dict['tool_choice'] = self.tool_choice.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if stream (nullable) is None
        # and model_fields_set contains the field
        if self.stream is None and "stream" in self.model_fields_set:
            _dict['stream'] = None

        # set to None if temperature (nullable) is None
        # and model_fields_set contains the field
        if self.temperature is None and "temperature" in self.model_fields_set:
            _dict['temperature'] = None

        # set to None if top_p (nullable) is None
        # and model_fields_set contains the field
        if self.top_p is None and "top_p" in self.model_fields_set:
            _dict['top_p'] = None

        # set to None if n (nullable) is None
        # and model_fields_set contains the field
        if self.n is None and "n" in self.model_fields_set:
            _dict['n'] = None

        # set to None if max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_tokens is None and "max_tokens" in self.model_fields_set:
            _dict['max_tokens'] = None

        # set to None if max_completion_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_completion_tokens is None and "max_completion_tokens" in self.model_fields_set:
            _dict['max_completion_tokens'] = None

        # set to None if stop (nullable) is None
        # and model_fields_set contains the field
        if self.stop is None and "stop" in self.model_fields_set:
            _dict['stop'] = None

        # set to None if frequency_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.frequency_penalty is None and "frequency_penalty" in self.model_fields_set:
            _dict['frequency_penalty'] = None

        # set to None if presence_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.presence_penalty is None and "presence_penalty" in self.model_fields_set:
            _dict['presence_penalty'] = None

        # set to None if logprobs (nullable) is None
        # and model_fields_set contains the field
        if self.logprobs is None and "logprobs" in self.model_fields_set:
            _dict['logprobs'] = None

        # set to None if top_logprobs (nullable) is None
        # and model_fields_set contains the field
        if self.top_logprobs is None and "top_logprobs" in self.model_fields_set:
            _dict['top_logprobs'] = None

        # set to None if seed (nullable) is None
        # and model_fields_set contains the field
        if self.seed is None and "seed" in self.model_fields_set:
            _dict['seed'] = None

        # set to None if top_k (nullable) is None
        # and model_fields_set contains the field
        if self.top_k is None and "top_k" in self.model_fields_set:
            _dict['top_k'] = None

        # set to None if min_p (nullable) is None
        # and model_fields_set contains the field
        if self.min_p is None and "min_p" in self.model_fields_set:
            _dict['min_p'] = None

        # set to None if repetition_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.repetition_penalty is None and "repetition_penalty" in self.model_fields_set:
            _dict['repetition_penalty'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateChatCompletionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "model": obj.get("model"),
            "messages": [ChatCompletionMessage.from_dict(_item) for _item in obj["messages"]] if obj.get("messages") is not None else None,
            "stream": obj.get("stream") if obj.get("stream") is not None else False,
            "stream_options": CreateChatCompletionRequestStreamOptions.from_dict(obj["stream_options"]) if obj.get("stream_options") is not None else None,
            "temperature": obj.get("temperature"),
            "top_p": obj.get("top_p"),
            "n": obj.get("n"),
            "max_tokens": obj.get("max_tokens"),
            "max_completion_tokens": obj.get("max_completion_tokens"),
            "stop": CreateChatCompletionRequestStop.from_dict(obj["stop"]) if obj.get("stop") is not None else None,
            "frequency_penalty": obj.get("frequency_penalty"),
            "presence_penalty": obj.get("presence_penalty"),
            "logprobs": obj.get("logprobs"),
            "top_logprobs": obj.get("top_logprobs"),
            "logit_bias": obj.get("logit_bias"),
            "response_format": CreateChatCompletionRequestResponseFormat.from_dict(obj["response_format"]) if obj.get("response_format") is not None else None,
            "seed": obj.get("seed"),
            "tools": [CreateChatCompletionRequestToolsInner.from_dict(_item) for _item in obj["tools"]] if obj.get("tools") is not None else None,
            "tool_choice": CreateChatCompletionRequestToolChoice.from_dict(obj["tool_choice"]) if obj.get("tool_choice") is not None else None,
            "parallel_tool_calls": obj.get("parallel_tool_calls"),
            "reasoning_effort": obj.get("reasoning_effort"),
            "top_k": obj.get("top_k"),
            "min_p": obj.get("min_p"),
            "repetition_penalty": obj.get("repetition_penalty"),
            "min_tokens": obj.get("min_tokens"),
            "echo": obj.get("echo"),
            "user": obj.get("user")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


