# coding: utf-8

"""
    ai& API

    Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from aiand.models.create_response_response_error import CreateResponseResponseError
from aiand.models.create_response_response_incomplete_details import CreateResponseResponseIncompleteDetails
from aiand.models.create_response_response_output_inner import CreateResponseResponseOutputInner
from aiand.models.create_response_response_reasoning import CreateResponseResponseReasoning
from aiand.models.create_response_response_tool_choice import CreateResponseResponseToolChoice
from aiand.models.response_usage import ResponseUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateResponseResponse(BaseModel):
    """
    CreateResponseResponse
    """ # noqa: E501
    id: StrictStr = Field(description="Unique identifier for this response.")
    object: StrictStr = Field(description="The object type — always \"response\".")
    status: StrictStr = Field(description="The status of the response generation.")
    created_at: Union[StrictFloat, StrictInt] = Field(description="Unix timestamp (in seconds) of when this response was created.")
    completed_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix timestamp of completion. Only present when status is completed.")
    model: StrictStr = Field(description="The model used to generate the response.")
    output: List[CreateResponseResponseOutputInner] = Field(description="An array of content items generated by the model.")
    error: Optional[CreateResponseResponseError] = None
    incomplete_details: Optional[CreateResponseResponseIncompleteDetails] = None
    instructions: Optional[StrictStr] = None
    metadata: Optional[Dict[str, StrictStr]] = None
    temperature: Optional[Union[StrictFloat, StrictInt]] = None
    top_p: Optional[Union[StrictFloat, StrictInt]] = None
    max_output_tokens: Optional[StrictInt] = None
    tools: Optional[List[Dict[str, Any]]] = None
    tool_choice: Optional[CreateResponseResponseToolChoice] = None
    parallel_tool_calls: Optional[StrictBool] = None
    truncation: Optional[StrictStr] = None
    previous_response_id: Optional[StrictStr] = None
    reasoning: Optional[CreateResponseResponseReasoning] = None
    text: Optional[Dict[str, Any]] = None
    top_logprobs: Optional[StrictInt] = None
    usage: Optional[ResponseUsage] = Field(default=None, description="Token usage details for this response.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "object", "status", "created_at", "completed_at", "model", "output", "error", "incomplete_details", "instructions", "metadata", "temperature", "top_p", "max_output_tokens", "tools", "tool_choice", "parallel_tool_calls", "truncation", "previous_response_id", "reasoning", "text", "top_logprobs", "usage"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['response']):
            raise ValueError("must be one of enum values ('response')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['completed', 'failed', 'in_progress', 'cancelled', 'queued', 'incomplete']):
            raise ValueError("must be one of enum values ('completed', 'failed', 'in_progress', 'cancelled', 'queued', 'incomplete')")
        return value

    @field_validator('truncation')
    def truncation_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['auto', 'disabled']):
            raise ValueError("must be one of enum values ('auto', 'disabled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateResponseResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in output (list)
        _items = []
        if self.output:
            for _item_output in self.output:
                if _item_output:
                    _items.append(_item_output.to_dict())
            _dict['output'] = _items
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of incomplete_details
        if self.incomplete_details:
            _dict['incomplete_details'] = self.incomplete_details.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tool_choice
        if self.tool_choice:
            _dict['tool_choice'] = self.tool_choice.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reasoning
        if self.reasoning:
            _dict['reasoning'] = self.reasoning.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if instructions (nullable) is None
        # and model_fields_set contains the field
        if self.instructions is None and "instructions" in self.model_fields_set:
            _dict['instructions'] = None

        # set to None if temperature (nullable) is None
        # and model_fields_set contains the field
        if self.temperature is None and "temperature" in self.model_fields_set:
            _dict['temperature'] = None

        # set to None if top_p (nullable) is None
        # and model_fields_set contains the field
        if self.top_p is None and "top_p" in self.model_fields_set:
            _dict['top_p'] = None

        # set to None if max_output_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.max_output_tokens is None and "max_output_tokens" in self.model_fields_set:
            _dict['max_output_tokens'] = None

        # set to None if truncation (nullable) is None
        # and model_fields_set contains the field
        if self.truncation is None and "truncation" in self.model_fields_set:
            _dict['truncation'] = None

        # set to None if previous_response_id (nullable) is None
        # and model_fields_set contains the field
        if self.previous_response_id is None and "previous_response_id" in self.model_fields_set:
            _dict['previous_response_id'] = None

        # set to None if top_logprobs (nullable) is None
        # and model_fields_set contains the field
        if self.top_logprobs is None and "top_logprobs" in self.model_fields_set:
            _dict['top_logprobs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateResponseResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "completed_at": obj.get("completed_at"),
            "model": obj.get("model"),
            "output": [CreateResponseResponseOutputInner.from_dict(_item) for _item in obj["output"]] if obj.get("output") is not None else None,
            "error": CreateResponseResponseError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "incomplete_details": CreateResponseResponseIncompleteDetails.from_dict(obj["incomplete_details"]) if obj.get("incomplete_details") is not None else None,
            "instructions": obj.get("instructions"),
            "metadata": obj.get("metadata"),
            "temperature": obj.get("temperature"),
            "top_p": obj.get("top_p"),
            "max_output_tokens": obj.get("max_output_tokens"),
            "tools": obj.get("tools"),
            "tool_choice": CreateResponseResponseToolChoice.from_dict(obj["tool_choice"]) if obj.get("tool_choice") is not None else None,
            "parallel_tool_calls": obj.get("parallel_tool_calls"),
            "truncation": obj.get("truncation"),
            "previous_response_id": obj.get("previous_response_id"),
            "reasoning": CreateResponseResponseReasoning.from_dict(obj["reasoning"]) if obj.get("reasoning") is not None else None,
            "text": obj.get("text"),
            "top_logprobs": obj.get("top_logprobs"),
            "usage": ResponseUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


