# coding: utf-8

"""
    ai& API

    Unified spec covering inference, files, and other public surfaces. Drop-in compatible with OpenAI and Anthropic SDKs.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from aiand.models.file_object import FileObject
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UploadObject(BaseModel):
    """
    UploadObject
    """ # noqa: E501
    id: StrictStr = Field(description="Stable upload session id with `upload-` prefix")
    object: StrictStr
    bytes: StrictInt = Field(description="Declared total size of the file being uploaded")
    created_at: StrictInt = Field(description="Unix timestamp")
    expires_at: StrictInt = Field(description="Unix timestamp (1 hour from creation by default)")
    filename: Optional[StrictStr]
    purpose: StrictStr = Field(description="One of `vision`, `video`, `audio`, or `document`. Determines size, MIME limits, and which models can reference the file. Optional for single-shot file uploads when the API can infer it from MIME type.")
    status: StrictStr
    file: Optional[FileObject] = Field(description="Populated once status is `completed`")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "object", "bytes", "created_at", "expires_at", "filename", "purpose", "status", "file"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['upload']):
            raise ValueError("must be one of enum values ('upload')")
        return value

    @field_validator('purpose')
    def purpose_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['vision', 'video', 'audio', 'document']):
            raise ValueError("must be one of enum values ('vision', 'video', 'audio', 'document')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'completed', 'cancelled', 'expired']):
            raise ValueError("must be one of enum values ('pending', 'completed', 'cancelled', 'expired')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UploadObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file
        if self.file:
            _dict['file'] = self.file.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if filename (nullable) is None
        # and model_fields_set contains the field
        if self.filename is None and "filename" in self.model_fields_set:
            _dict['filename'] = None

        # set to None if file (nullable) is None
        # and model_fields_set contains the field
        if self.file is None and "file" in self.model_fields_set:
            _dict['file'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UploadObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "bytes": obj.get("bytes"),
            "created_at": obj.get("created_at"),
            "expires_at": obj.get("expires_at"),
            "filename": obj.get("filename"),
            "purpose": obj.get("purpose"),
            "status": obj.get("status"),
            "file": FileObject.from_dict(obj["file"]) if obj.get("file") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


